language: kotlin
sudo: false

jdk:
  - oraclejdk8

before_install:
  - "chmod +x gradlew"

script:
  - "./gradlew test check"

notifications:
  email:
    - christoph.pickl@gmail.com

before_cache:
  - "rm -f $HOME/.gradle/caches/modules-2/modules-2.lock"

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
