CREATE TABLE PartnerDbo (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  category     INTEGER       NOT NULL,
  deletedByMyc BOOLEAN       NOT NULL,
  favourited   BOOLEAN       NOT NULL,
  idMyc        VARCHAR(512)  NOT NULL,
  ignored      BOOLEAN       NOT NULL,
  linkMyclubs  VARCHAR(128)  NOT NULL,
  linkPartner  VARCHAR(128)  NOT NULL,
  maxCredits   TINYINT       NOT NULL,
  name         VARCHAR(512)  NOT NULL,
  note         VARCHAR(5120) NOT NULL,
  picture      BLOB(1048576),
  rating       VARCHAR(128)  NOT NULL,
  shortName    VARCHAR(512)  NOT NULL,
  wishlisted   BOOLEAN       NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE PartnerDbo_addresses (
  PartnerDbo_id BIGINT NOT NULL,
  addresses     VARCHAR(255)
);

ALTER TABLE PartnerDbo
  ADD CONSTRAINT UK_3po4fjydrqy2skbuw60bi0bpk UNIQUE (idMyc);
ALTER TABLE PartnerDbo
  ADD CONSTRAINT UK_flyiquema8mef568aj5vn3d4m UNIQUE (shortName);
ALTER TABLE PartnerDbo_addresses
  ADD CONSTRAINT FKfae8r0snge969uvevfiwe54fl FOREIGN KEY (PartnerDbo_id) REFERENCES PartnerDbo
