CREATE TABLE PartnerDbo (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  category     INTEGER       NOT NULL,
  deletedByMyc BOOLEAN       NOT NULL,
  favourited   BOOLEAN       NOT NULL,
  idMyc        VARCHAR(512)  NOT NULL,
  ignored      BOOLEAN       NOT NULL,
  linkMyclubs  VARCHAR(128)  NOT NULL,
  linkPartner  VARCHAR(128)  NOT NULL,
  maxCredits   TINYINT       NOT NULL,
  name         VARCHAR(512)  NOT NULL,
  note         VARCHAR(5120) NOT NULL,
  picture      BLOB(1048576),
  rating       VARCHAR(128)  NOT NULL,
  shortName    VARCHAR(512)  NOT NULL,
  wishlisted   BOOLEAN       NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE PartnerDbo_addresses (
  PartnerDbo_id BIGINT NOT NULL,
  addresses     VARCHAR(255)
);

CREATE TABLE PartnerDbo_tags (
  PartnerDbo_id BIGINT NOT NULL,
  tags          VARCHAR(255)
);

CREATE TABLE PartnerDbo_finishedActivities (
  PartnerDbo_id BIGINT       NOT NULL,
  date          TIMESTAMP    NOT NULL,
  title         VARCHAR(512) NOT NULL
);

ALTER TABLE PartnerDbo
  ADD CONSTRAINT PartnerDboConstraintUniqueIdMyc UNIQUE (idMyc);

ALTER TABLE PartnerDbo
  ADD CONSTRAINT PartnerDboConstraintUniqueShortName UNIQUE (shortName);

ALTER TABLE PartnerDbo_addresses
  ADD CONSTRAINT PartnerDbo_addresses_ConstraintForeignKey FOREIGN KEY (PartnerDbo_id) REFERENCES PartnerDbo;

ALTER TABLE PartnerDbo_tags
  ADD CONSTRAINT PartnerDbo_tags_ConstraintForeignKey FOREIGN KEY (PartnerDbo_id) REFERENCES PartnerDbo;

ALTER TABLE PartnerDbo_finishedActivities
  ADD CONSTRAINT PartnerDbo_finishedActivities_ConstraintForeignKey FOREIGN KEY (PartnerDbo_id) REFERENCES PartnerDbo;
