/*
CREATE TABLE tbl_partner (
  id BIGINT NOT NULL PRIMARY KEY,
  idMyc VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  shortName VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  rating VARCHAR(255) NOT NULL,
  deletedByMyc BOOLEAN NOT NULL,
  favourited BOOLEAN NOT NULL,
  wishlisted BOOLEAN NOT NULL,
  ignored BOOLEAN NOT NULL,
  category VARCHAR(255) NOT NULL,
  linkMyclubsSite VARCHAR(255) NOT NULL,
  linkPartnerSite VARCHAR(255) NOT NULL

);
*/
CREATE TABLE PartnerDbo (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  address         VARCHAR(255) NOT NULL,
  category        INTEGER      NOT NULL,
  deletedByMyc    BOOLEAN      NOT NULL,
  favourited      BOOLEAN      NOT NULL,
  idMyc           VARCHAR(255) NOT NULL,
  ignored         BOOLEAN      NOT NULL,
  linkMyclubsSite VARCHAR(255) NOT NULL,
  linkPartnerSite VARCHAR(255) NOT NULL,
  name            VARCHAR(255) NOT NULL,
  rating          VARCHAR(255) NOT NULL,
  shortName       VARCHAR(255) NOT NULL,
  wishlisted      BOOLEAN      NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE PartnerDbo
  ADD CONSTRAINT UK_hyy77cobs9kk75ldp3euwsmxb UNIQUE (idMyc);

ALTER TABLE PartnerDbo
  ADD CONSTRAINT UK_7hw7iigwhdnbvxakvhv8ed2qg UNIQUE (shortName);
