CREATE TABLE PartnerDbo (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1 ),
  address         VARCHAR(512)  NOT NULL,
  category        INTEGER       NOT NULL,
  deletedByMyc    BOOLEAN       NOT NULL,
  favourited      BOOLEAN       NOT NULL,
  idMyc           VARCHAR(512)  NOT NULL,
  ignored         BOOLEAN       NOT NULL,
  linkMyclubsSite VARCHAR(128)  NOT NULL,
  linkPartnerSite VARCHAR(128)  NOT NULL,
  maxCredits      TINYINT       NOT NULL,
  name            VARCHAR(512)  NOT NULL,
  note            VARCHAR(5120) NOT NULL,
  picture         BLOB(1048576),
  rating          VARCHAR(128)  NOT NULL,
  shortName       VARCHAR(512)  NOT NULL,
  wishlisted      BOOLEAN       NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE PartnerDbo
  ADD CONSTRAINT PartnerDboConstraintUniqueIdMyc UNIQUE (idMyc);

ALTER TABLE PartnerDbo
  ADD CONSTRAINT PartnerDboConstraintUniqueShortName UNIQUE (shortName);
