
CREATE TABLE UpcomingActivityDbo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
  date TIMESTAMP     NOT NULL,
  title VARCHAR(512) NOT NULL,
  partnerId BIGINT,
  PRIMARY KEY (id)
);

ALTER TABLE UpcomingActivityDbo
  ADD CONSTRAINT UpcomingActivityDbo_partnerId_ConstraintForeignKey FOREIGN KEY (partnerId) REFERENCES PartnerDbo;
